"""Notifications table fixes

Revision ID: 80530957d835
Revises: cf52931a86bb
Create Date: 2023-09-30 14:49:14.805163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80530957d835'
down_revision: Union[str, None] = 'cf52931a86bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('notifications_recipient_fkey', 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'users', ['user_id'], ['id'])
    op.drop_column('notifications', 'recipient')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('recipient', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key('notifications_recipient_fkey', 'notifications', 'users', ['recipient'], ['id'])
    op.drop_column('notifications', 'user_id')
    # ### end Alembic commands ###
